#!/usr/bin/env python3
"""Regenerate the standalone `email_triage_standalone.py` bundle from the package and tests.

The bundle is a convenience copy for machines where installing the package is not
practical. It is generated, not hand-edited:

    python tools/build_single_file.py          # rewrite email_triage_standalone.py
    python tools/build_single_file.py --check  # fail if the bundle is stale
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path


_PATCH_TARGET_RE = re.compile(r'"email_triage\.[a-z_]+\.([A-Za-z_0-9]+)"')


ROOT = Path(__file__).resolve().parent.parent
PACKAGE = ROOT / "src" / "email_triage"
TESTS = ROOT / "tests"
BUNDLE = ROOT / "email_triage_standalone.py"

#: Dependency order. Every module only references names defined above it.
MODULE_ORDER = (
    "models",
    "feedback",
    "providers",
    "config",
    "backends",
    "desktop",
    "accessibility",
    "safety",
    "classifier",
    "pipeline",
    "actions",
    "agent",
    "graph",
    "owa",
    "local_mailbox",
    "apply",
    "runtime",
    "live_probe",
    "cli",
)

TEST_ORDER = (
    "test_models",
    "test_providers",
    "test_config",
    "test_backends",
    "test_desktop",
    "test_accessibility",
    "test_safety",
    "test_classifier",
    "test_local_mailbox",
    "test_graph",
    "test_owa",
    "test_pipeline",
    "test_actions",
    "test_agent",
    "test_apply",
    "test_runtime",
    "test_cli",
    "test_live_probe",
)

HEADER = '''#!/usr/bin/env python3
"""Single-file Outlook email triage: local Ollama screening, agent sorting, drafts.

Generated by tools/build_single_file.py — edit src/email_triage/, not this file.

Preview the plan without touching the mailbox:
    python email_triage_standalone.py --input samples/inbox.jsonl

Sort the real mailbox from Outlook already open in Edge (no Entra admin):
    python email_triage_standalone.py --owa --apply --watch

Sort the real mailbox with a registered Graph app (moves, categories, unsent drafts; never sends):
    python email_triage_standalone.py --apply

Run the bundled tests (no Microsoft or cloud AI calls):
    python email_triage_standalone.py --self-test
"""
'''

FOOTER = '''

def _run_self_tests() -> int:
    suite = unittest.defaultTestLoader.loadTestsFromModule(sys.modules[__name__])
    result = unittest.TextTestRunner(verbosity=2).run(suite)
    return 0 if result.wasSuccessful() else 1


def main(argv: list[str] | None = None) -> int:
    arguments = list(sys.argv[1:] if argv is None else argv)
    if "--self-test" in arguments:
        return _run_self_tests()
    return _cli_main(arguments)


if __name__ == "__main__":
    raise SystemExit(main())
'''

TRAILING_MAIN_BLOCKS = (
    'if __name__ == "__main__":\n    raise SystemExit(main())\n',
    'if __name__ == "__main__":\n    unittest.main()\n',
)


class BundleError(RuntimeError):
    """Raised when the sources cannot be bundled safely."""


def _strip_imports(source: str, local_modules: set[str]) -> tuple[str, list[str]]:
    """Remove intra-project imports; return the body and the hoisted stdlib imports."""

    tree = ast.parse(source)
    drop: set[int] = set()
    hoisted: list[str] = []
    lines = source.splitlines()
    for node in tree.body:
        if isinstance(node, ast.ImportFrom):
            module = node.module or ""
            root = module.split(".")[0]
            if module == "__future__" or root == "email_triage" or module in local_modules:
                drop.update(range(node.lineno - 1, (node.end_lineno or node.lineno)))
                continue
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            drop.update(range(node.lineno - 1, (node.end_lineno or node.lineno)))
            hoisted.append("\n".join(lines[node.lineno - 1 : node.end_lineno]))
    body = "\n".join(line for index, line in enumerate(lines) if index not in drop)
    return body.strip("\n"), hoisted


def _top_level_names(source: str) -> set[str]:
    names: set[str] = set()
    for node in ast.parse(source).body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            names.add(node.name)
        elif isinstance(node, ast.Assign):
            names.update(
                target.id for target in node.targets if isinstance(target, ast.Name)
            )
    return names


def _banner(title: str) -> str:
    rule = "# " + "-" * 73
    return f"{rule}\n# {title}\n{rule}\n"


def render() -> str:
    local_test_modules = set(TEST_ORDER)
    sections: list[str] = []
    hoisted: list[str] = []
    seen_names: dict[str, str] = {}

    sources: list[tuple[str, str, Path]] = [
        (name, f"email_triage/{name}.py", PACKAGE / f"{name}.py") for name in MODULE_ORDER
    ]
    sources += [(name, f"tests/{name}.py", TESTS / f"{name}.py") for name in TEST_ORDER]

    for name, label, path in sources:
        if not path.exists():
            raise BundleError(f"missing source module: {path}")
        source = path.read_text(encoding="utf-8")
        for block in TRAILING_MAIN_BLOCKS:
            if source.endswith(block):
                source = source[: -len(block)]
        if name == "cli":
            source = source.replace("def main(argv:", "def _cli_main(argv:")
        if name.startswith("test_"):
            # Patch targets must point at this bundle instead of the installed package.
            source = _PATCH_TARGET_RE.sub(r'__name__ + ".\1"', source)
        body, imports = _strip_imports(source, local_test_modules)
        hoisted.extend(imports)
        for defined in _top_level_names(body):
            if defined in seen_names and not defined.startswith("test_"):
                raise BundleError(
                    f"name {defined!r} is defined in both {seen_names[defined]} and {label}"
                )
            seen_names[defined] = label
        sections.append(_banner(label) + "\n" + body + "\n")

    import_block = "\n".join(sorted(dict.fromkeys(hoisted), key=_import_sort_key))
    parts = [HEADER, "\nfrom __future__ import annotations\n\n", import_block, "\n\n"]
    parts.append('__version__ = "0.1.0"\n\n\n')
    parts.append("\n\n".join(sections))
    return "".join(parts).rstrip("\n") + "\n" + FOOTER


def _import_sort_key(statement: str) -> tuple[int, str]:
    return (0 if statement.startswith("import ") else 1, statement)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero when the bundle differs from the generated output.",
    )
    args = parser.parse_args(argv)
    try:
        rendered = render()
    except BundleError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    if args.check:
        current = BUNDLE.read_text(encoding="utf-8") if BUNDLE.exists() else ""
        if current != rendered:
            print(
                "email_triage_standalone.py is stale; run python tools/build_single_file.py",
                file=sys.stderr,
            )
            return 1
        print("email_triage_standalone.py is up to date.")
        return 0
    BUNDLE.write_text(rendered, encoding="utf-8")
    print(f"wrote {BUNDLE} ({len(rendered.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
